# Generated by Django 5.2.7 on 2025-10-11 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sp500',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
