# Generated by Django 5.2.7 on 2025-10-13 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest_app', '0002_alter_sp500_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSeriesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('date', models.DateTimeField()),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.BigIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='SP500',
        ),
        migrations.AddIndex(
            model_name='timeseriesdata',
            index=models.Index(fields=['symbol', 'date'], name='backtest_ap_symbol_6113c2_idx'),
        ),
        migrations.AddIndex(
            model_name='timeseriesdata',
            index=models.Index(fields=['date'], name='backtest_ap_date_dd0757_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='timeseriesdata',
            unique_together={('symbol', 'date')},
        ),
        migrations.CreateModel(
            name='SP500',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('backtest_app.timeseriesdata',),
        ),
    ]
