# Generated by Django 5.2.7 on 2025-10-27 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backtest_app', '0003_timeseriesdata_delete_sp500_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SP500',
        ),
    ]
