# Generated by Django 5.2.7 on 2025-10-29 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest_app', '0004_delete_sp500'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BacktestingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instrument', models.CharField(max_length=50)),
                ('timeframe', models.CharField(max_length=10)),
                ('current_timestamp', models.DateTimeField(blank=True, null=True)),
                ('chart_state', models.JSONField(blank=True, null=True)),
                ('open_positions', models.JSONField(blank=True, null=True)),
                ('closed_positions', models.JSONField(blank=True, null=True)),
                ('account_state', models.JSONField(blank=True, null=True)),
                ('parameters', models.JSONField(blank=True, null=True)),
                ('result', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backtesting_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
